version: '2'

services:
    api-nginx:
        container_name: api_nginx
        image: nginx:latest
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:api.local"
            - "traefik.port=80"
            - "traefik.docker.network=web"
            - "traefik.default.protocol=http"
        volumes:
            - ./website_code/:/var/www/
            - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./.env:/var/www/.env
            - ./ssl/:/certs/
        depends_on: 
            - api-php
        networks:
            - api-network
            - web
            
    api-php:
        container_name: api_php
        build: .
        volumes:
            - ./website_code/:/var/www/
            - ./.env:/var/www/.env
            - ./scripts/install_laravel.sh:/root/install_laravel.sh
            - ./conf/php/local.ini:/usr/local/etc/php/conf.d/docker-php-local.ini

        networks:
            - api-network

    api-db:
        container_name: api_db
        image: mysql
        restart: always
        volumes:
            - ./db/:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: okay
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - api-network
            - web
    api-redis:
        container_name: api_redis
        image: redis:6.2-alpine
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes: 
            - ./cache/:/data
        ports:
            - 6379:6379
        networks:
            - api-network

    mailhog:  
        container_name: api_mail  
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
        networks:
            - api-network


        
            
    traefik:
        image: traefik:v1.7.33
        ports:
            - 8080:8080
            - 80:80
            - 444:443
        networks:
            - web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/acme.json:/acme.json
            - ./ssl/:/certs/
        container_name: traefik

networks:
    api-network:
        driver: bridge
    web:
        external: true
